// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddWorkDialog: typeof import('./src/components/aside/AddWorkDialog.vue')['default']
    AddWorkDialogControls: typeof import('./src/components/aside/AddWorkDialogControls.vue')['default']
    AppAside: typeof import('./src/components/aside/AppAside.vue')['default']
    AppAsideSkeleton: typeof import('./src/components/aside/AppAsideSkeleton.vue')['default']
    AppAsideWorksList: typeof import('./src/components/aside/AppAsideWorksList.vue')['default']
    AppAsideWorksListItem: typeof import('./src/components/aside/AppAsideWorksListItem.vue')['default']
    AppHeader: typeof import('./src/components/header/AppHeader.vue')['default']
    AppMain: typeof import('./src/components/main/AppMain.vue')['default']
    AppMainOptions: typeof import('./src/components/main/AppMainOptions.vue')['default']
    AppMainSkeleton: typeof import('./src/components/main/AppMainSkeleton.vue')['default']
    CellMaterial: typeof import('./src/components/main/table/CellMaterial.vue')['default']
    DeleteAllWorks: typeof import('./src/components/aside/DeleteAllWorks.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    MobileOptions: typeof import('./src/components/mobile/MobileOptions.vue')['default']
    MobileWorksList: typeof import('./src/components/mobile/MobileWorksList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/main/table/Table.vue')['default']
    TableGrouped: typeof import('./src/components/main/table/TableGrouped.vue')['default']
  }
}
