// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddWork: typeof import('./src/components/aside/AddWork.vue')['default']
    'AddWork old': typeof import('./src/components/aside/AddWork old.vue')['default']
    AddWorkDialog: typeof import('./src/components/addWork/AddWorkDialog.vue')['default']
    AddWorkInput: typeof import('./src/components/aside/AddWorkInput.vue')['default']
    AddWorkItem: typeof import('./src/components/aside/AddWorkItem.vue')['default']
    AppAside: typeof import('./src/components/aside/AppAside.vue')['default']
    AppHeader: typeof import('./src/components/header/AppHeader.vue')['default']
    AppMain: typeof import('./src/components/main/AppMain.vue')['default']
    copy: typeof import('./src/components/aside/WorksList copy.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    old: typeof import('./src/components/aside/AddWork old.vue')['default']
    WorksList: typeof import('./src/components/aside/WorksList.vue')['default']
    WorksListItem: typeof import('./src/components/aside/WorksListItem.vue')['default']
  }
}
