// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddWork: typeof import('./src/components/aside/AddWork.vue')['default']
    AddWorkControls: typeof import('./src/components/aside/AddWorkControls.vue')['default']
    AddWorkDialog: typeof import('./src/components/addWork/AddWorkDialog.vue')['default']
    AddWorkInput: typeof import('./src/components/aside/AddWorkInput.vue')['default']
    AddWorkItem: typeof import('./src/components/aside/AddWorkItem.vue')['default']
    AppAside: typeof import('./src/components/aside/AppAside.vue')['default']
    AppHeader: typeof import('./src/components/header/AppHeader.vue')['default']
    AppMain: typeof import('./src/components/main/AppMain.vue')['default']
    AppMainOptions: typeof import('./src/components/main/AppMainOptions.vue')['default']
    AppMainTable: typeof import('./src/components/main/table/AppMainTable.vue')['default']
    AppMainTableGrouped: typeof import('./src/components/main/table/AppMainTableGrouped.vue')['default']
    CellMaterial: typeof import('./src/components/main/table/CellMaterial.vue')['default']
    copy: typeof import('./src/components/main/table/Table copy.vue')['default']
    DeleteAllWorks: typeof import('./src/components/aside/DeleteAllWorks.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HeaderOptions: typeof import('./src/components/main/HeaderOptions.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    old: typeof import('./src/components/aside/AddWork old.vue')['default']
    Table: typeof import('./src/components/main/table/Table.vue')['default']
    TableGrouped: typeof import('./src/components/main/table/TableGrouped.vue')['default']
    WorksList: typeof import('./src/components/aside/WorksList.vue')['default']
    WorksListItem: typeof import('./src/components/aside/WorksListItem.vue')['default']
  }
}
